# Generated by Django 4.0.4 on 2023-04-17 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_user_create_time_user_last_login_time_user_login_ip_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='last_login_time',
        ),
        migrations.AddField(
            model_name='user',
            name='login_time',
            field=models.DateTimeField(auto_now=True, verbose_name='登录时间'),
        ),
    ]
