# Generated by Django 4.0.4 on 2023-04-17 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_user_last_login_time_user_login_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_admin',
            field=models.BooleanField(default=False, verbose_name='是否是管理员'),
        ),
        migrations.AddField(
            model_name='user',
            name='online_count',
            field=models.IntegerField(default=10, verbose_name='剩余在线问答次数'),
        ),
        migrations.AddField(
            model_name='user',
            name='status',
            field=models.IntegerField(default=0, verbose_name='账号状态'),
        ),
        migrations.AddField(
            model_name='user',
            name='upload_count',
            field=models.IntegerField(default=0, verbose_name='上传题目数量'),
        ),
        # migrations.AlterField(
        #     model_name='user',
        #     name='login_time',
        #     field=models.DateTimeField(auto_now=True, verbose_name='登录时间'),
        #     options={'timezone': True}
        # )
    ]
