# Generated by Django 4.0.4 on 2023-05-14 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_rename_search_text_searchhistory_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='online_count',
        ),
        migrations.AddField(
            model_name='user',
            name='tokens',
            field=models.IntegerField(default=10, editable=False, verbose_name='剩余token数量'),
        ),
    ]
