# Generated by Django 4.0.4 on 2023-05-27 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_alter_user_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_admin',
        ),
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
        migrations.AddField(
            model_name='user',
            name='has_permission',
            field=models.BooleanField(default=False, verbose_name='是否具有通过chatgpt生成题目的权限'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(editable=False, max_length=254, unique=True, verbose_name='邮箱'),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(editable=False, max_length=100, verbose_name='密码'),
        ),
        migrations.AlterField(
            model_name='user',
            name='status',
            field=models.BooleanField(default=True, verbose_name='账号状态'),
        ),
        migrations.AlterField(
            model_name='user',
            name='tokens',
            field=models.IntegerField(default=10000, verbose_name='剩余token数量'),
        ),
    ]
